# Configuration for Alacritty, the GPU enhanced terminal emulator.
[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
startup_mode = "Fullscreen"
opacity = 0.7
blur = true
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 16.0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "N", mods = "Command", action = "CreateNewWindow" }
]

[scrolling]
history = 10000
multiplier = 3 