{
  # Shared base packages for all macOS profiles.
  taps = [
    "nguyenphutrong/tap"
  ];

  brews = [
    "coreutils"
    "duf"
    "dust"
    "gnu-getopt"
    "fd"
    "mas"
    "zoxide"
    "uv"
    "poetry"
    "poppler"
    "python@3.12"
    "cmake"
    "duckdb"
    "maven"
    "neovim"
    "pkg-config"
    "git-lfs"
    "go"
    "node"
    "shellcheck"
    "kafka"
    "yamlresume"
    "fzf"
    "yq"
    "glow"
    "neofetch"
    "tldr"
    "gnupg"
    "sops"
    "age"
    "awscli"
    "aws-iam-authenticator"
    "helm"
    "terraform-docs"
    "tflint"
  ];

  casks = [
    "temurin@11"
    "temurin@17"
    "slack"
    "discord"
    "microsoft-office"
    "cursor"
    "antigravity"
    "claude-code"
    "docker-desktop"
    "jetbrains-toolbox"
    "postman"
    "visual-studio-code"
    "alacritty"
    "karabiner-elements"
    "rectangle"
    "the-unarchiver"
    "bitwarden"
    "brave-browser"
    "google-chrome"
    "claude"
    "lm-studio"
    "insync"
    "obsidian"
    "quotio"
    # "spotify"
    "whatsapp"
    "vlc"
    "font-jetbrains-mono-nerd-font"
    "font-fira-code-nerd-font"
    "font-hack-nerd-font"
    "font-meslo-lg-nerd-font"
    "font-inter"
    "font-source-serif-4"
    "font-source-sans-3"
    "font-sauce-code-pro-nerd-font"
    "font-ubuntu-mono-nerd-font"
    "font-dejavu-sans-mono-nerd-font"
    "font-inconsolata-nerd-font"
    "tailscale-app"
    "copilot-cli"
    # "steam"
  ];

  masApps = {};
}
